production:
  GITHUB_KEY: ''
  GITHUB_SECRET: ''
  SMTP_HOST: 'smtp.mandrillapp.com'
  SMTP_PORT: '587'
  SMTP_USERNAME: ''
  SMTP_PASSWORD: ''
  DEFAULT_EMAIL_SENDER: 'app@email.com'
  ADMIN_EMAIL: ''
  CONTACT_EMAIL: 'contact@domain.com'