production:
  SECRET_KEY_BASE: ''
  DOMAIN: ''
  GITHUB_KEY: ''
  GITHUB_SECRET: ''
  SMTP_HOST: 'smtp.mandrillapp.com'
  SMTP_PORT: '587'
  SMTP_USERNAME: ''
  SMTP_PASSWORD: ''
  DEFAULT_EMAIL_SENDER: 'app@email.com'
  ADMIN_EMAIL: ''
  CONTACT_EMAIL: 'contact@domain.com'
  GA_TRACKING_CODE: ''
  SEGMENT_IO_WRITE_KEY: ''
  OAUTH2_CLIENT_ID: ''
  OAUTH2_CLIENT_SECRET: ''
